//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Exam_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Exam()
        {
            this.Std_exam = new HashSet<Std_exam>();
        }
    
        public int Enumber { get; set; }
        public Nullable<System.DateTime> Edate { get; set; }
        public double Eduration { get; set; }
        public string Edescription { get; set; }
        public Nullable<int> NumOfTF { get; set; }
        public Nullable<int> NumOfMcq { get; set; }
        public Nullable<int> CrsId { get; set; }
    
        public virtual Course Course { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Std_exam> Std_exam { get; set; }
    }
}
