//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Exam_App
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class OnlineExam : DbContext
    {
        public OnlineExam()
            : base("name=OnlineExam")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Course> Courses { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Exam> Exams { get; set; }
        public virtual DbSet<Instructor> Instructors { get; set; }
        public virtual DbSet<Ques_Choices> Ques_Choices { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<Std_exam> Std_exam { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Topic> Topics { get; set; }
    
        public virtual ObjectResult<string> Delete_Choice(Nullable<int> q_ID, string choice)
        {
            var q_IDParameter = q_ID.HasValue ?
                new ObjectParameter("Q_ID", q_ID) :
                new ObjectParameter("Q_ID", typeof(int));
    
            var choiceParameter = choice != null ?
                new ObjectParameter("choice", choice) :
                new ObjectParameter("choice", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Delete_Choice", q_IDParameter, choiceParameter);
        }
    
        public virtual ObjectResult<string> Delete_Course_byName(string name)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Delete_Course_byName", nameParameter);
        }
    
        public virtual ObjectResult<string> Delete_Crs_Topic(Nullable<int> crs_Id, string topic)
        {
            var crs_IdParameter = crs_Id.HasValue ?
                new ObjectParameter("Crs_Id", crs_Id) :
                new ObjectParameter("Crs_Id", typeof(int));
    
            var topicParameter = topic != null ?
                new ObjectParameter("topic", topic) :
                new ObjectParameter("topic", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Delete_Crs_Topic", crs_IdParameter, topicParameter);
        }
    
        public virtual ObjectResult<string> Delete_Department(string dname)
        {
            var dnameParameter = dname != null ?
                new ObjectParameter("Dname", dname) :
                new ObjectParameter("Dname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Delete_Department", dnameParameter);
        }
    
        public virtual ObjectResult<string> Delete_Instructor(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Delete_Instructor", idParameter);
        }
    
        public virtual ObjectResult<string> Delete_Question(Nullable<int> q_id)
        {
            var q_idParameter = q_id.HasValue ?
                new ObjectParameter("Q_id", q_id) :
                new ObjectParameter("Q_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Delete_Question", q_idParameter);
        }
    
        public virtual ObjectResult<string> Delete_Student(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Delete_Student", idParameter);
        }
    
        public virtual ObjectResult<generateExam_Result> generateExam(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<generateExam_Result>("generateExam", idParameter);
        }
    
        public virtual ObjectResult<getCoursesByDeptID_Result> getCoursesByDeptID(Nullable<int> deptID)
        {
            var deptIDParameter = deptID.HasValue ?
                new ObjectParameter("deptID", deptID) :
                new ObjectParameter("deptID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getCoursesByDeptID_Result>("getCoursesByDeptID", deptIDParameter);
        }
    
        public virtual ObjectResult<string> Insert_Choice(Nullable<int> q_id, string choice, string ch_body)
        {
            var q_idParameter = q_id.HasValue ?
                new ObjectParameter("q_id", q_id) :
                new ObjectParameter("q_id", typeof(int));
    
            var choiceParameter = choice != null ?
                new ObjectParameter("choice", choice) :
                new ObjectParameter("choice", typeof(string));
    
            var ch_bodyParameter = ch_body != null ?
                new ObjectParameter("ch_body", ch_body) :
                new ObjectParameter("ch_body", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Insert_Choice", q_idParameter, choiceParameter, ch_bodyParameter);
        }
    
        public virtual ObjectResult<string> Insert_Course(string name)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Insert_Course", nameParameter);
        }
    
        public virtual ObjectResult<string> Insert_Crs_Topic(Nullable<int> crs_ID, string topic)
        {
            var crs_IDParameter = crs_ID.HasValue ?
                new ObjectParameter("Crs_ID", crs_ID) :
                new ObjectParameter("Crs_ID", typeof(int));
    
            var topicParameter = topic != null ?
                new ObjectParameter("Topic", topic) :
                new ObjectParameter("Topic", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Insert_Crs_Topic", crs_IDParameter, topicParameter);
        }
    
        public virtual ObjectResult<string> Insert_Department(string name, Nullable<int> manger_id)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var manger_idParameter = manger_id.HasValue ?
                new ObjectParameter("manger_id", manger_id) :
                new ObjectParameter("manger_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Insert_Department", nameParameter, manger_idParameter);
        }
    
        public virtual ObjectResult<string> Insert_Instructor(string name, Nullable<int> dept_id)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var dept_idParameter = dept_id.HasValue ?
                new ObjectParameter("dept_id", dept_id) :
                new ObjectParameter("dept_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Insert_Instructor", nameParameter, dept_idParameter);
        }
    
        public virtual ObjectResult<string> Insert_Question(Nullable<int> q_ID, string q_Body, string q_Type, Nullable<int> q_degree, string q_Answer, Nullable<int> crs_ID, string choice_Body1, string choice_Body2, string choice_Body3, string choice_Body4)
        {
            var q_IDParameter = q_ID.HasValue ?
                new ObjectParameter("Q_ID", q_ID) :
                new ObjectParameter("Q_ID", typeof(int));
    
            var q_BodyParameter = q_Body != null ?
                new ObjectParameter("Q_Body", q_Body) :
                new ObjectParameter("Q_Body", typeof(string));
    
            var q_TypeParameter = q_Type != null ?
                new ObjectParameter("Q_Type", q_Type) :
                new ObjectParameter("Q_Type", typeof(string));
    
            var q_degreeParameter = q_degree.HasValue ?
                new ObjectParameter("Q_degree", q_degree) :
                new ObjectParameter("Q_degree", typeof(int));
    
            var q_AnswerParameter = q_Answer != null ?
                new ObjectParameter("Q_Answer", q_Answer) :
                new ObjectParameter("Q_Answer", typeof(string));
    
            var crs_IDParameter = crs_ID.HasValue ?
                new ObjectParameter("Crs_ID", crs_ID) :
                new ObjectParameter("Crs_ID", typeof(int));
    
            var choice_Body1Parameter = choice_Body1 != null ?
                new ObjectParameter("Choice_Body1", choice_Body1) :
                new ObjectParameter("Choice_Body1", typeof(string));
    
            var choice_Body2Parameter = choice_Body2 != null ?
                new ObjectParameter("Choice_Body2", choice_Body2) :
                new ObjectParameter("Choice_Body2", typeof(string));
    
            var choice_Body3Parameter = choice_Body3 != null ?
                new ObjectParameter("Choice_Body3", choice_Body3) :
                new ObjectParameter("Choice_Body3", typeof(string));
    
            var choice_Body4Parameter = choice_Body4 != null ?
                new ObjectParameter("Choice_Body4", choice_Body4) :
                new ObjectParameter("Choice_Body4", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Insert_Question", q_IDParameter, q_BodyParameter, q_TypeParameter, q_degreeParameter, q_AnswerParameter, crs_IDParameter, choice_Body1Parameter, choice_Body2Parameter, choice_Body3Parameter, choice_Body4Parameter);
        }
    
        public virtual int Insert_Std_Answer(Nullable<int> sid, Nullable<int> eid, Nullable<int> qid, string stdAnsw)
        {
            var sidParameter = sid.HasValue ?
                new ObjectParameter("sid", sid) :
                new ObjectParameter("sid", typeof(int));
    
            var eidParameter = eid.HasValue ?
                new ObjectParameter("eid", eid) :
                new ObjectParameter("eid", typeof(int));
    
            var qidParameter = qid.HasValue ?
                new ObjectParameter("qid", qid) :
                new ObjectParameter("qid", typeof(int));
    
            var stdAnswParameter = stdAnsw != null ?
                new ObjectParameter("stdAnsw", stdAnsw) :
                new ObjectParameter("stdAnsw", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Insert_Std_Answer", sidParameter, eidParameter, qidParameter, stdAnswParameter);
        }
    
        public virtual ObjectResult<string> Insert_Student(string fname, string lname, Nullable<System.DateTime> birth_date, string address, Nullable<int> department_id)
        {
            var fnameParameter = fname != null ?
                new ObjectParameter("Fname", fname) :
                new ObjectParameter("Fname", typeof(string));
    
            var lnameParameter = lname != null ?
                new ObjectParameter("Lname", lname) :
                new ObjectParameter("Lname", typeof(string));
    
            var birth_dateParameter = birth_date.HasValue ?
                new ObjectParameter("birth_date", birth_date) :
                new ObjectParameter("birth_date", typeof(System.DateTime));
    
            var addressParameter = address != null ?
                new ObjectParameter("Address", address) :
                new ObjectParameter("Address", typeof(string));
    
            var department_idParameter = department_id.HasValue ?
                new ObjectParameter("department_id", department_id) :
                new ObjectParameter("department_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Insert_Student", fnameParameter, lnameParameter, birth_dateParameter, addressParameter, department_idParameter);
        }
    
        public virtual int newStudnet(string fname, string lname, Nullable<System.DateTime> dob, string address, Nullable<int> deptid)
        {
            var fnameParameter = fname != null ?
                new ObjectParameter("fname", fname) :
                new ObjectParameter("fname", typeof(string));
    
            var lnameParameter = lname != null ?
                new ObjectParameter("lname", lname) :
                new ObjectParameter("lname", typeof(string));
    
            var dobParameter = dob.HasValue ?
                new ObjectParameter("dob", dob) :
                new ObjectParameter("dob", typeof(System.DateTime));
    
            var addressParameter = address != null ?
                new ObjectParameter("address", address) :
                new ObjectParameter("address", typeof(string));
    
            var deptidParameter = deptid.HasValue ?
                new ObjectParameter("deptid", deptid) :
                new ObjectParameter("deptid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("newStudnet", fnameParameter, lnameParameter, dobParameter, addressParameter, deptidParameter);
        }
    
        public virtual ObjectResult<Select_Course_byName_Result> Select_Course_byName(string name)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Select_Course_byName_Result>("Select_Course_byName", nameParameter);
        }
    
        public virtual ObjectResult<string> Select_Course_Topics(Nullable<int> crs_id)
        {
            var crs_idParameter = crs_id.HasValue ?
                new ObjectParameter("crs_id", crs_id) :
                new ObjectParameter("crs_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Select_Course_Topics", crs_idParameter);
        }
    
        public virtual ObjectResult<Select_Department_Result> Select_Department(string name)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Select_Department_Result>("Select_Department", nameParameter);
        }
    
        public virtual ObjectResult<Select_Exam_Result> Select_Exam(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Select_Exam_Result>("Select_Exam", idParameter);
        }
    
        public virtual ObjectResult<Select_Instructor_Result> Select_Instructor(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Select_Instructor_Result>("Select_Instructor", idParameter);
        }
    
        public virtual ObjectResult<Select_MCQ_Question_Result> Select_MCQ_Question(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Select_MCQ_Question_Result>("Select_MCQ_Question", idParameter);
        }
    
        public virtual ObjectResult<Select_Question_Result> Select_Question(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Select_Question_Result>("Select_Question", idParameter);
        }
    
        public virtual ObjectResult<Select_Student_Result> Select_Student(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Select_Student_Result>("Select_Student", idParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual int Student_Answer_Question(Nullable<int> st_id, Nullable<int> ex_id, Nullable<int> q_id, string ans)
        {
            var st_idParameter = st_id.HasValue ?
                new ObjectParameter("st_id", st_id) :
                new ObjectParameter("st_id", typeof(int));
    
            var ex_idParameter = ex_id.HasValue ?
                new ObjectParameter("ex_id", ex_id) :
                new ObjectParameter("ex_id", typeof(int));
    
            var q_idParameter = q_id.HasValue ?
                new ObjectParameter("q_id", q_id) :
                new ObjectParameter("q_id", typeof(int));
    
            var ansParameter = ans != null ?
                new ObjectParameter("ans", ans) :
                new ObjectParameter("ans", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Student_Answer_Question", st_idParameter, ex_idParameter, q_idParameter, ansParameter);
        }
    
        public virtual ObjectResult<string> Update_Choice(Nullable<int> q_id, string choice, string ch_body)
        {
            var q_idParameter = q_id.HasValue ?
                new ObjectParameter("q_id", q_id) :
                new ObjectParameter("q_id", typeof(int));
    
            var choiceParameter = choice != null ?
                new ObjectParameter("choice", choice) :
                new ObjectParameter("choice", typeof(string));
    
            var ch_bodyParameter = ch_body != null ?
                new ObjectParameter("ch_body", ch_body) :
                new ObjectParameter("ch_body", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Update_Choice", q_idParameter, choiceParameter, ch_bodyParameter);
        }
    
        public virtual int Update_Course(Nullable<int> id, string name)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_Course", idParameter, nameParameter);
        }
    
        public virtual ObjectResult<string> Update_Department(string name, Nullable<int> manger_id)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var manger_idParameter = manger_id.HasValue ?
                new ObjectParameter("manger_id", manger_id) :
                new ObjectParameter("manger_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Update_Department", nameParameter, manger_idParameter);
        }
    
        public virtual ObjectResult<string> Update_Instructor(Nullable<int> id, string name, Nullable<int> dept_id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var dept_idParameter = dept_id.HasValue ?
                new ObjectParameter("dept_id", dept_id) :
                new ObjectParameter("dept_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Update_Instructor", idParameter, nameParameter, dept_idParameter);
        }
    
        public virtual ObjectResult<string> Update_Q_Model_Answer(Nullable<int> q_ID, string q_Answer)
        {
            var q_IDParameter = q_ID.HasValue ?
                new ObjectParameter("Q_ID", q_ID) :
                new ObjectParameter("Q_ID", typeof(int));
    
            var q_AnswerParameter = q_Answer != null ?
                new ObjectParameter("Q_Answer", q_Answer) :
                new ObjectParameter("Q_Answer", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Update_Q_Model_Answer", q_IDParameter, q_AnswerParameter);
        }
    
        public virtual ObjectResult<string> Update_Question(Nullable<int> q_id, string body, string type, string model_ans, Nullable<int> crs_id)
        {
            var q_idParameter = q_id.HasValue ?
                new ObjectParameter("q_id", q_id) :
                new ObjectParameter("q_id", typeof(int));
    
            var bodyParameter = body != null ?
                new ObjectParameter("body", body) :
                new ObjectParameter("body", typeof(string));
    
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            var model_ansParameter = model_ans != null ?
                new ObjectParameter("model_ans", model_ans) :
                new ObjectParameter("model_ans", typeof(string));
    
            var crs_idParameter = crs_id.HasValue ?
                new ObjectParameter("crs_id", crs_id) :
                new ObjectParameter("crs_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Update_Question", q_idParameter, bodyParameter, typeParameter, model_ansParameter, crs_idParameter);
        }
    
        public virtual ObjectResult<string> Update_Student(Nullable<int> st_id, string fname, string lname, Nullable<System.DateTime> birth_date, string address, Nullable<int> department_id)
        {
            var st_idParameter = st_id.HasValue ?
                new ObjectParameter("st_id", st_id) :
                new ObjectParameter("st_id", typeof(int));
    
            var fnameParameter = fname != null ?
                new ObjectParameter("Fname", fname) :
                new ObjectParameter("Fname", typeof(string));
    
            var lnameParameter = lname != null ?
                new ObjectParameter("Lname", lname) :
                new ObjectParameter("Lname", typeof(string));
    
            var birth_dateParameter = birth_date.HasValue ?
                new ObjectParameter("birth_date", birth_date) :
                new ObjectParameter("birth_date", typeof(System.DateTime));
    
            var addressParameter = address != null ?
                new ObjectParameter("Address", address) :
                new ObjectParameter("Address", typeof(string));
    
            var department_idParameter = department_id.HasValue ?
                new ObjectParameter("department_id", department_id) :
                new ObjectParameter("department_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Update_Student", st_idParameter, fnameParameter, lnameParameter, birth_dateParameter, addressParameter, department_idParameter);
        }
    
        public virtual int updateStudent(Nullable<int> id, string fname, string lname, Nullable<System.DateTime> dob, string address, Nullable<int> deptid)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var fnameParameter = fname != null ?
                new ObjectParameter("fname", fname) :
                new ObjectParameter("fname", typeof(string));
    
            var lnameParameter = lname != null ?
                new ObjectParameter("lname", lname) :
                new ObjectParameter("lname", typeof(string));
    
            var dobParameter = dob.HasValue ?
                new ObjectParameter("dob", dob) :
                new ObjectParameter("dob", typeof(System.DateTime));
    
            var addressParameter = address != null ?
                new ObjectParameter("address", address) :
                new ObjectParameter("address", typeof(string));
    
            var deptidParameter = deptid.HasValue ?
                new ObjectParameter("deptid", deptid) :
                new ObjectParameter("deptid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updateStudent", idParameter, fnameParameter, lnameParameter, dobParameter, addressParameter, deptidParameter);
        }
    }
}
