//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Exam_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Question()
        {
            this.Ques_Choices = new HashSet<Ques_Choices>();
            this.Std_exam = new HashSet<Std_exam>();
        }
    
        public int QuesId { get; set; }
        public string Type { get; set; }
        public Nullable<double> Degree { get; set; }
        public string Qcontent { get; set; }
        public string Answer { get; set; }
        public Nullable<int> CrsId { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Course Course1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ques_Choices> Ques_Choices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Std_exam> Std_exam { get; set; }
    }
}
