//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Exam_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class Topic
    {
        public int TopId { get; set; }
        public int CrsId { get; set; }
        public string Topname { get; set; }
    
        public virtual Course Course { get; set; }
    }
}
